/**
 * phase4.test.ts
 *
 * Tests for Phase 4 additions:
 * - Custom swarms router (CRUD operations, Zod validation, agent structure)
 * - SwarmBuilder export document format
 * - ASSESS LLC branding in exports
 * - GitHub rename (verified via package.json)
 * - marketing_lead routing bug fix in seed data
 */

import { describe, it, expect } from "vitest";

// ─── Custom Swarms Router ─────────────────────────────────────────────────────

describe("custom swarms router", () => {
  it("swarms router file exports swarmsRouter", async () => {
    const mod = await import("./routers/swarms");
    expect(mod.swarmsRouter).toBeDefined();
    expect(typeof mod.swarmsRouter).toBe("object");
  });

  it("swarmsRouter has all required procedures", async () => {
    const { swarmsRouter } = await import("./routers/swarms");
    const router = swarmsRouter as unknown as { _def: { procedures: Record<string, unknown> } };
    const procedures = router._def?.procedures ?? {};
    const procedureNames = Object.keys(procedures);
    expect(procedureNames).toContain("list");
    expect(procedureNames).toContain("get");
    expect(procedureNames).toContain("create");
    expect(procedureNames).toContain("update");
    expect(procedureNames).toContain("delete");
  });

  it("swarmsRouter is wired into the main appRouter", async () => {
    const { appRouter } = await import("./routers");
    const router = appRouter as unknown as { _def: { procedures: Record<string, unknown> } };
    const procedures = router._def?.procedures ?? {};
    // tRPC flattens sub-routers as "swarms.list", "swarms.create", etc.
    const hasSwarms = Object.keys(procedures).some((k) => k.startsWith("swarms."));
    expect(hasSwarms).toBe(true);
  });
});

// ─── Agent Structure Validation ───────────────────────────────────────────────

describe("custom agent structure", () => {
  it("a valid CustomAgent has all required fields", () => {
    const agent = {
      id: "agent_1234_abc",
      name: "Research Lead",
      role: "Researches market trends and summarizes findings",
      systemPrompt: "You are a research specialist...",
      inputFrom: "user",
      outputTo: "agent_2",
      handoffCondition: "When research is complete, pass to Content Writer",
    };
    expect(agent.id).toBeTruthy();
    expect(agent.name).toBeTruthy();
    expect(agent.role).toBeTruthy();
    expect(agent.systemPrompt).toBeTruthy();
    expect(agent.inputFrom).toBeTruthy();
    expect(agent.outputTo).toBeTruthy();
  });

  it("agent with sourceExampleSlug carries provenance", () => {
    const agent = {
      id: "agent_1234_abc",
      name: "Content Writer",
      role: "Writes content based on research",
      systemPrompt: "You are a content writer...",
      inputFrom: "Research Lead",
      outputTo: "user",
      handoffCondition: "When draft is complete",
      sourceExampleSlug: "blog-post-seo-optimized",
      sourceExampleTitle: "SEO-Optimized Blog Post",
    };
    expect(agent.sourceExampleSlug).toBe("blog-post-seo-optimized");
    expect(agent.sourceExampleTitle).toBe("SEO-Optimized Blog Post");
  });
});

// ─── Export Document Format ───────────────────────────────────────────────────

describe("swarm export document format", () => {
  // Replicate the buildCustomExportDocument logic to test it independently
  function buildCustomExportDocument(
    name: string,
    goal: string,
    topology: string,
    agents: Array<{
      id: string;
      name: string;
      role: string;
      systemPrompt: string;
      inputFrom: string;
      outputTo: string;
      handoffCondition: string;
      sourceExampleTitle?: string;
    }>
  ): string {
    const lines: string[] = [
      `# ${name}`,
      ``,
      `**Goal:** ${goal || "Not specified"}`,
      `**Topology:** ${topology}`,
      `**Agents:** ${agents.length}`,
      `**Built with:** Promptwright — by ASSESS LLC`,
      ``,
      `---`,
      ``,
    ];
    agents.forEach((agent, idx) => {
      lines.push(`### Agent ${idx + 1}: ${agent.name}`);
      lines.push(``);
      lines.push(`**Role:** ${agent.role}`);
      if (agent.inputFrom) lines.push(`**Receives input from:** ${agent.inputFrom}`);
      if (agent.outputTo) lines.push(`**Sends output to:** ${agent.outputTo}`);
      if (agent.handoffCondition) lines.push(`**Handoff condition:** ${agent.handoffCondition}`);
      if (agent.sourceExampleTitle) {
        lines.push(`**System prompt source:** Example Library — "${agent.sourceExampleTitle}"`);
      }
      lines.push(``);
      lines.push(`**System Prompt:**`);
      lines.push(``);
      lines.push("```");
      lines.push(agent.systemPrompt);
      lines.push("```");
      lines.push(``);
      lines.push(`---`);
      lines.push(``);
    });
    lines.push(`*Generated by Promptwright — by ASSESS LLC*`);
    return lines.join("\n");
  }

  const testAgents = [
    {
      id: "agent_1",
      name: "Research Lead",
      role: "Researches market trends",
      systemPrompt: "You are a research specialist. Your job is to gather and synthesize market data.",
      inputFrom: "user",
      outputTo: "Content Writer",
      handoffCondition: "When research is complete",
    },
    {
      id: "agent_2",
      name: "Content Writer",
      role: "Writes content based on research",
      systemPrompt: "You are a content writer. Your job is to turn research into compelling copy.",
      inputFrom: "Research Lead",
      outputTo: "user",
      handoffCondition: "When draft is complete",
      sourceExampleTitle: "SEO-Optimized Blog Post",
    },
  ];

  it("export document contains the swarm name as H1", () => {
    const doc = buildCustomExportDocument("ASSESS Business Swarm", "Run weekly business review", "sequential", testAgents);
    expect(doc).toContain("# ASSESS Business Swarm");
  });

  it("export document contains ASSESS LLC branding", () => {
    const doc = buildCustomExportDocument("Test Swarm", "Test goal", "sequential", testAgents);
    expect(doc).toContain("ASSESS LLC");
    expect(doc).toContain("Promptwright — by ASSESS LLC");
  });

  it("export document contains all agent names", () => {
    const doc = buildCustomExportDocument("Test Swarm", "Test goal", "sequential", testAgents);
    expect(doc).toContain("### Agent 1: Research Lead");
    expect(doc).toContain("### Agent 2: Content Writer");
  });

  it("export document contains agent system prompts in code blocks", () => {
    const doc = buildCustomExportDocument("Test Swarm", "Test goal", "sequential", testAgents);
    expect(doc).toContain("```\nYou are a research specialist.");
    expect(doc).toContain("```\nYou are a content writer.");
  });

  it("export document shows source example provenance when present", () => {
    const doc = buildCustomExportDocument("Test Swarm", "Test goal", "sequential", testAgents);
    expect(doc).toContain('System prompt source:** Example Library — "SEO-Optimized Blog Post"');
  });

  it("export document shows handoff conditions", () => {
    const doc = buildCustomExportDocument("Test Swarm", "Test goal", "sequential", testAgents);
    expect(doc).toContain("**Handoff condition:** When research is complete");
    expect(doc).toContain("**Handoff condition:** When draft is complete");
  });

  it("export document shows routing (inputFrom / outputTo)", () => {
    const doc = buildCustomExportDocument("Test Swarm", "Test goal", "sequential", testAgents);
    expect(doc).toContain("**Receives input from:** user");
    expect(doc).toContain("**Sends output to:** Content Writer");
  });

  it("export document ends with Promptwright attribution", () => {
    const doc = buildCustomExportDocument("Test Swarm", "Test goal", "sequential", testAgents);
    expect(doc.trim().endsWith("*Generated by Promptwright — by ASSESS LLC*")).toBe(true);
  });
});

// ─── Seed Data Bug Fix ────────────────────────────────────────────────────────

describe("swarm seed data correctness", () => {
  it("seed file does not contain marketing_lead routing to finance_lead (bug fix)", async () => {
    const fs = await import("fs");
    const path = await import("path");
    const seedPath = path.join(process.cwd(), "scripts", "seed-swarm-templates.mjs");
    const content = fs.readFileSync(seedPath, "utf-8");
    // The bug was marketing_lead outputTo: "finance_lead" — should be "orchestrator"
    expect(content).not.toContain('"marketing_lead" → finance_lead');
    // Verify the fix: marketing_lead should route to orchestrator
    const marketingLeadSection = content.match(/marketing_lead[\s\S]{0,500}outputTo/);
    if (marketingLeadSection) {
      expect(marketingLeadSection[0]).not.toContain("finance_lead");
    }
  });

  it("seed file defines 8 swarm templates", async () => {
    const fs = await import("fs");
    const path = await import("path");
    const seedPath = path.join(process.cwd(), "scripts", "seed-swarm-templates.mjs");
    const content = fs.readFileSync(seedPath, "utf-8");
    // Count slug: occurrences as a proxy for template count
    const slugMatches = content.match(/slug:/g);
    expect(slugMatches).not.toBeNull();
    // There should be at least 8 slug: entries (one per template)
    expect(slugMatches!.length).toBeGreaterThanOrEqual(8);
  });
});

// ─── ASSESS LLC Branding ──────────────────────────────────────────────────────

describe("ASSESS LLC branding", () => {
  it("README contains ASSESS LLC attribution", async () => {
    const fs = await import("fs");
    const path = await import("path");
    const readmePath = path.join(process.cwd(), "README.md");
    const content = fs.readFileSync(readmePath, "utf-8");
    expect(content).toContain("ASSESS LLC");
  });

  it("package.json name is promptwright", async () => {
    const fs = await import("fs");
    const path = await import("path");
    const pkgPath = path.join(process.cwd(), "package.json");
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
    expect(pkg.name).toBe("promptwright");
  });
});

// ─── SwarmBuilder Component File ─────────────────────────────────────────────

describe("SwarmBuilder component", () => {
  it("SwarmBuilder.tsx exists in components directory", async () => {
    const fs = await import("fs");
    const path = await import("path");
    const componentPath = path.join(process.cwd(), "client", "src", "components", "SwarmBuilder.tsx");
    expect(fs.existsSync(componentPath)).toBe(true);
  });

  it("SwarmBuilder.tsx exports SwarmBuilder as default and MySwarms as named", async () => {
    const fs = await import("fs");
    const path = await import("path");
    const componentPath = path.join(process.cwd(), "client", "src", "components", "SwarmBuilder.tsx");
    const content = fs.readFileSync(componentPath, "utf-8");
    expect(content).toContain("export default function SwarmBuilder");
    expect(content).toContain("export { MySwarms }");
  });

  it("SwarmBuilder.tsx references the example picker modal", async () => {
    const fs = await import("fs");
    const path = await import("path");
    const componentPath = path.join(process.cwd(), "client", "src", "components", "SwarmBuilder.tsx");
    const content = fs.readFileSync(componentPath, "utf-8");
    expect(content).toContain("ExamplePicker");
    expect(content).toContain("Pick from Examples");
    expect(content).toContain("trpc.knowledge.getExamples.useQuery");
  });

  it("SwarmBuilder.tsx uses trpc.swarms for CRUD operations", async () => {
    const fs = await import("fs");
    const path = await import("path");
    const componentPath = path.join(process.cwd(), "client", "src", "components", "SwarmBuilder.tsx");
    const content = fs.readFileSync(componentPath, "utf-8");
    expect(content).toContain("trpc.swarms.create.useMutation");
    expect(content).toContain("trpc.swarms.update.useMutation");
    expect(content).toContain("trpc.swarms.list.useQuery");
  });

  it("SwarmBuilder.tsx accepts initialSwarm prop and has useEffect to hydrate state", async () => {
    const fs = await import("fs");
    const path = await import("path");
    const componentPath = path.join(process.cwd(), "client", "src", "components", "SwarmBuilder.tsx");
    const content = fs.readFileSync(componentPath, "utf-8");
    // Prop is defined
    expect(content).toContain("initialSwarm?: SavedSwarmData | null");
    // useEffect hydrates from initialSwarm
    expect(content).toContain("useEffect(() => {");
    expect(content).toContain("if (!initialSwarm) return");
    expect(content).toContain("setAgents(initialSwarm.agents)");
    // SavedSwarmData type is exported
    expect(content).toContain("export type { CustomAgent, SavedSwarmData }");
  });

  it("SwarmComposer.tsx passes selectedSavedSwarm to SwarmBuilder", async () => {
    const fs = await import("fs");
    const path = await import("path");
    const composerPath = path.join(process.cwd(), "client", "src", "pages", "SwarmComposer.tsx");
    const content = fs.readFileSync(composerPath, "utf-8");
    // State is declared
    expect(content).toContain("selectedSavedSwarm");
    expect(content).toContain("setSelectedSavedSwarm");
    // Passed to SwarmBuilder
    expect(content).toContain("initialSwarm={selectedSavedSwarm}");
    // onLoad sets the swarm and switches mode
    expect(content).toContain("setSelectedSavedSwarm(swarm)");
    expect(content).toContain('setMode("build")');
  });

  it("SwarmBuilder.tsx includes topology selector with all 5 topologies", async () => {
    const fs = await import("fs");
    const path = await import("path");
    const componentPath = path.join(process.cwd(), "client", "src", "components", "SwarmBuilder.tsx");
    const content = fs.readFileSync(componentPath, "utf-8");
    expect(content).toContain('"sequential"');
    expect(content).toContain('"parallel"');
    expect(content).toContain('"hub-spoke"');
    expect(content).toContain('"hierarchical"');
    expect(content).toContain('"iterative"');
  });
});
